# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-26 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190424_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emai_active',
            field=models.BooleanField(default=False, verbose_name='邮箱是否激活'),
        ),
    ]
